
DATABASE: "sqlite"                                                                                          # only sqlite avaible for now (next versions may have mysql option)

DEFAULT_Gold: 100.00                                                                                        # default gold user get on first join
DEFAULT_Silver : 50.00                                                                                      # default silver user get on first join

VALUE_OF_1_GOLD_IN_SILVER: 100                                                                              # used in baltop and in the excange (if enabled)

EXCHANGE_CURRENCYES: true                                                                                   # true to enable /exchange

DEFAULT_VAULT_I_NTERACTION: "SILVER"                                                                        # vault is not created to support >1 currencyes, in order to connect with others
                                                                                                            # plugin I suggest to use "SILVER" (u can use "GOLD" too) and enable exchange

WITHDRAW_&_REDEEM: true                                                                                     # enable or disable command to withdraw and redeem

GOLD_INGOT_NAME_COLOR: "ยง6"
SILVER_INGOT_NAME_COLOR: "ยง7"

WITHDRAWED_GOLD_INGOT_NAME_SINGOLAR: "GOLD BAR"
WITHDRAWED_GOLD_INGOT_NAME_PLURAL: "GOLD BARS"

WITHDRAWED_SILVER_INGOT_NAME_SINGOLAR: "SILVER BAR"
WITHDRAWED_SILVER_INGOT_NAME_PLURAL: "SILVER BARS"

WITHDRAW_ITEM_LORE: "ยง1Redeem this item with command /redeem"                                               # use this in lore to tell user what to do
